#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Feb 22 01:32:11 +03 2020
# SW Build 2188600 on Wed Apr  4 18:39:19 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim tb_top_func_impl -key {Post-Implementation:sim_1:Functional:tb_top} -tclbatch tb_top.tcl -view /home/topalc/Desktop/ibex-master/build/lowrisc_ibex_top_artya7_100_0.1/synth-vivado/tb_top_behav1.wcfg -log simulate.log
